module.exports = {
  espanol: {
    titulo: "Imágenes 360",
    frasecita: "renders digitales, fotografía, panorámicos 360, aplicativos web",
    botonIngreso: "ingresa",
    botonContacto: "contacto",
    segundaSeccionUno: "Renders Digitales, Fotografía,",
    segundaSeccionDos: "Panorámicos 360, Aplicativos web y más!",
    segundaSeccionTres: "Renders Productos",
    segundaSeccionCuatro: "Panorámicos 360",
    segundaSeccionCinco: "arquitectura, espacios",
    segundaSeccionSeis: "Aplicativos web",
    segundaSeccionSiete: "React, RubyOnRails, JS",
    ultimaSeccionUna: "Mira mi portafolio...",
    panos360: "panorámicos 360",
    digital: "digital",
    fotografia: "fotografía",
    radar: "radar",
    renders: "renders",
    gifs360: "gifs 360",
    productos: "productos",
    espacios: "espacios",
    otros: "otros",
    fotoproductos: "fotografía productos",
    joyas: "joyas",
    componentes: "componentes",
    cuadros: "cuadros",
    galeria: "galería imágenes",
    detalles: "detalles",
    paisajes: "paisajes",
    urbano: "urbano",
    texturas: "texturas",
    muelles: "muelles",
    cuadrados: "cuadrados",
    lost: "perdidos",
    monuments: "monumentos",
    perspective: "perspectiva",
    programacion: "programación",
    cirilico: "cirílico",
    morse: "morse",
    calculadora: "calculadora",
    equilibrio: "equilibrio"
  },
  ingles: {
    titulo: "360 Images",
    frasecita: "digital renders, photography, 360 panoramics, web apps",
    botonIngreso: "enter",
    botonContacto: "contact me",
    segundaSeccionUno: "Digital Renders, Photography,",
    segundaSeccionDos: "360 Panoramics, Web Apps & more!",
    segundaSeccionTres: "Product Renders",
    segundaSeccionCuatro: "360 Panoramics",
    segundaSeccionCinco: "architecture, spaces",
    segundaSeccionSeis: "Web Apps",
    segundaSeccionSiete: "React, RubyOnRails, JS",
    ultimaSeccionUna: "Check my portfolio...",
    panos360: "360 panoramics",
    digital: "digital",
    fotografia: "photography",
    radar: "radar",
    renders: "renders",
    gifs360: "gifs 360",
    productos: "products",
    espacios: "spaces",
    otros: "others",
    fotoproductos: "product photography",
    joyas: "jewellery",
    componentes: "components",
    cuadros: "tableaux",
    galeria: "image gallery",
    detalles: "details",
    paisajes: "landscapes",
    urbano: "urban",
    texturas: "textures",
    muelles: "ports",
    cuadrados: "square",
    lost: "lost",
    monuments: "monuments",
    perspective: "perspective",
    programacion: "programming",
    cirilico: "cyrillic",
    morse: "morse",
    calculadora: "calculator",
    equilibrio: "equilibrium"
  },
  frances: {
    titulo: "Images 360",
    frasecita: "renders digitales, photographie, panoramiques 360, web apps",
    botonIngreso: "entrer",
    botonContacto: "me contacter",
    segundaSeccionUno: "Render Digitales, Photographie,",
    segundaSeccionDos: "Panoramiques 360, Web Apps et plus!",
    segundaSeccionTres: "Renders des produits",
    segundaSeccionCuatro: "Panoramiques 360",
    segundaSeccionCinco: "architecture, espaces",
    segundaSeccionSeis: "Web Apps",
    segundaSeccionSiete: "React, RubyOnRails, JS",
    ultimaSeccionUna: "Regardez mon travail...",
    panos360: "panoramiques 360",
    digital: "digitale",
    fotografia: "photographie",
    radar: "radar",
    renders: "renders",
    gifs360: "gifs 360",
    productos: "productos",
    espacios: "espacios",
    otros: "otros",
    fotoproductos: "fotografía productos",
    joyas: "joyas",
    componentes: "componentes",
    cuadros: "cuadros",
    galeria: "galería imágenes",
    detalles: "detalles",
    paisajes: "paisajes",
    urbano: "urbano",
    texturas: "texturas",
    muelles: "muelles",
    cuadrados: "cuadrados",
    programacion: "programación",
    cirilico: "cirílico",
    morse: "morse",
    calculadora: "calculadora",
    equilibrio: "equilibrio"
  },
  italiano: {
    titulo: "Imagini 360",
    frasecita: "render digitali, fotografia, panoramica 360, web apps",
    botonIngreso: "entrare",
    botonContacto: "contattami",
    segundaSeccionUno: "Renders Digitali, Fotografia,",
    segundaSeccionDos: "Panoramica 360, Web Apps e più!",
    segundaSeccionTres: "Renders di Prodotti",
    segundaSeccionCuatro: "Panoramica 360",
    segundaSeccionCinco: "architettura, spazi",
    segundaSeccionSeis: "Web Apps",
    segundaSeccionSiete: "React, RubyOnRails, JS",
    ultimaSeccionUna: "Guarda il mio portafolio...",
    panos360: "panoramica 360",
    digital: "digitale",
    fotografia: "fotografia",
    radar: "radare",
    renders: "renders",
    gifs360: "gifs 360",
    productos: "productos",
    espacios: "espacios",
    otros: "otros",
    fotoproductos: "fotografía productos",
    joyas: "joyas",
    componentes: "componentes",
    cuadros: "cuadros",
    galeria: "galería imágenes",
    detalles: "detalles",
    paisajes: "paisajes",
    urbano: "urbano",
    texturas: "texturas",
    muelles: "muelles",
    cuadrados: "cuadrados",
    programacion: "programación",
    cirilico: "cirílico",
    morse: "morse",
    calculadora: "calculadora",
    equilibrio: "equilibrio"
  },
  portugues: {
    titulo: "Imagens 360",
    frasecita: "renders digitales, fotografia, panoramicas 360, web apps",
    botonIngreso: "entra",
    botonContacto: "me-contactar",
    segundaSeccionUno: "Renders Digitales, Fotografia,",
    segundaSeccionDos: "Panoramicas 360, Web Apps e mais!",
    segundaSeccionTres: "Renders de Produtos",
    segundaSeccionCuatro: "Panoramicas 360",
    segundaSeccionCinco: "arquitetura, espacios",
    segundaSeccionSeis: "Web Apps",
    segundaSeccionSiete: "React, RubyOnRails, JS",
    ultimaSeccionUna: "Olhe o meu portfólio...",
    panos360: "panoramicas 360",
    digital: "digital",
    fotografia: "fotografia",
    radar: "radar",
    renders: "renders",
    gifs360: "gifs 360",
    productos: "productos",
    espacios: "espacios",
    otros: "otros",
    fotoproductos: "fotografía productos",
    joyas: "joyas",
    componentes: "componentes",
    cuadros: "cuadros",
    galeria: "galería imágenes",
    detalles: "detalles",
    paisajes: "paisajes",
    urbano: "urbano",
    texturas: "texturas",
    muelles: "muelles",
    cuadrados: "cuadrados",
    programacion: "programación",
    cirilico: "cirílico",
    morse: "morse",
    calculadora: "calculadora",
    equilibrio: "equilibrio"
  },
  aleman: {
    titulo: "360 Bilder",
    frasecita: "digital renders, fotografie, 360 panoramik, web apps",
    botonIngreso: "eingeben",
    botonContacto: "kontakt",
    segundaSeccionUno: "Digital Renders, Fotografie,",
    segundaSeccionDos: "360 Panoramik, Web Apps & mehr!",
    segundaSeccionTres: "Produkt Renders",
    segundaSeccionCuatro: "360 Panoramik",
    segundaSeccionCinco: "architektur, räume",
    segundaSeccionSeis: "Web Apps",
    segundaSeccionSiete: "React, RubyOnRails, JS",
    ultimaSeccionUna: "Mein portfolio...",
    panos360: "360 panoramik",
    digital: "digital",
    fotografia: "fotografie",
    radar: "radar",
    renders: "renders",
    gifs360: "gifs 360",
    productos: "productos",
    espacios: "espacios",
    otros: "otros",
    fotoproductos: "fotografía productos",
    joyas: "joyas",
    componentes: "componentes",
    cuadros: "cuadros",
    galeria: "galería imágenes",
    detalles: "detalles",
    paisajes: "paisajes",
    urbano: "urbano",
    texturas: "texturas",
    muelles: "muelles",
    cuadrados: "cuadrados",
    programacion: "programación",
    cirilico: "cirílico",
    morse: "morse",
    calculadora: "calculadora",
    equilibrio: "equilibrio"
  },
}
