module.exports = {

  slideRenderOtr: {
    name: "Render Variados",
    image: [
      'http://imagenes360.net/fotos/renders/otros/otros_01.JPG',
      'http://imagenes360.net/fotos/renders/otros/otros_02.JPG',
      'http://imagenes360.net/fotos/renders/otros/otros_03.JPG',
      'http://imagenes360.net/fotos/renders/otros/otros_04.JPG',
      'http://imagenes360.net/fotos/renders/otros/otros_05.JPG',
      'http://imagenes360.net/fotos/renders/otros/otros_06.JPG',
      'http://imagenes360.net/fotos/renders/otros/otros_07.JPG',
      'http://imagenes360.net/fotos/renders/otros/otros_08.JPG',
      'http://imagenes360.net/fotos/renders/otros/otros_09.jpg',
      'http://imagenes360.net/fotos/renders/otros/otros_10.jpg',
      'http://imagenes360.net/fotos/renders/otros/otros_11.jpg',
      'http://imagenes360.net/fotos/renders/otros/otros_12.jpg',
      'http://imagenes360.net/fotos/renders/otros/otros_13.jpg',
      'http://imagenes360.net/fotos/renders/otros/otros_14.jpg'
    ],
    commentsPerPic: [
      "Pirañas | Luces Caústicas",
      "Piraña | Texturas",
      "Piraña",
      "Naufragio | Texturas",
      "Naufragio | Texturas",
      "Naufragio | Texturas",
      "Chevrolet Vitara | Modelado",
      "Chevrolet Vitara | Modelado",
      "Sofa | Test Texturas",
      "Silo Cementero | Modelado",
      "Trofeo | Modelado",
      "Mostrador Joyas | Vista general",
      "Empaque Mariposas | Vista general",
      "Mesa Selección | Diseño Propio"
    ],
    description: "Los renders son imágenes ideales para visualizar un objeto o espacio que aún no existe o para diseñar reformas, texturas y decoración a uno existente.\nEstas gráficas son realizadas mediante técnicas de fotorealismo utlizando diferentes softwares de modelación 3D, renderizado y post producción.",
    logo1: "tridimax",
    logo2: "vray",
    logo3: "photoshop",
    logo4: "illustrator"
  },
  slideRenderProd: {
    name: "Render Productos",
    image: [
      'http://imagenes360.net/fotos/renders/prod/productos_01.JPG',
      'http://imagenes360.net/fotos/renders/prod/productos_02.JPG',
      'http://imagenes360.net/fotos/renders/prod/productos_03.JPG',
      'http://imagenes360.net/fotos/renders/prod/productos_04.jpg',
      'http://imagenes360.net/fotos/renders/prod/productos_05.JPG',
      'http://imagenes360.net/fotos/renders/prod/productos_06.JPG',
      'http://imagenes360.net/fotos/renders/prod/productos_07.JPG',
      'http://imagenes360.net/fotos/renders/prod/productos_08.jpg',
      'http://imagenes360.net/fotos/renders/prod/productos_09.jpg',
      'http://imagenes360.net/fotos/renders/prod/productos_10.jpg',
      'http://imagenes360.net/fotos/renders/prod/productos_11.JPG',
      'http://imagenes360.net/fotos/renders/prod/productos_12.jpg',
      'http://imagenes360.net/fotos/renders/prod/productos_13.jpg',
      'http://imagenes360.net/fotos/renders/prod/productos_14.jpg',
      'http://imagenes360.net/fotos/renders/prod/productos_15.jpg',
      'http://imagenes360.net/fotos/renders/prod/productos_16.JPG',
      'http://imagenes360.net/fotos/renders/prod/productos_17.JPG',
      'http://imagenes360.net/fotos/renders/prod/productos_18.JPG',
      'http://imagenes360.net/fotos/renders/prod/productos_19.JPG',
      'http://imagenes360.net/fotos/renders/prod/productos_20.JPG'
    ],
    commentsPerPic: [
      "Piraña Berebere | Lámpara",
      "Piraña Berebere | Set Completo",
      "Top Case | Top Case para ATV",
      "Velero Class Pirate | Full View",
      "Velero Class Pirate | Detalles",
      "Velero Class Pirate | Vista trasera",
      "Velero Class Pirate | Vista Delantera",
      "Sillón | Diseño Propio",
      "Sofá Boo | Perceptual",
      "Muebles Bar | Modelos",
      "Organizador Archivo Hitórico | Clínica Medellín",
      "Organizador Archivo Hitórico | Clínica Medellín",
      "Organizador Archivo Hitórico | Clínica Medellín",
      "Organizador Archivo Hitórico | Clínica Medellín",
      "Organizador Archivo Hitórico | Clínica Medellín",
      "Bar Móbil",
      "Despertador",
      "Servilletero",
      "Solpidem | Empaque Exterior",
      "Solpidem | Empaque Interior"
    ],
    description: "Los renders de productos son imágenes ideales para visualizar un objeto que aún no existe o para diseñar reformas, texturas y decoración a uno existente.\nEstas gráficas son realizadas mediante técnicas de fotorealismo utlizando diferentes softwares de modelación 3D, renderizado y post producción.",
    logo1: "tridimax",
    logo2: "vray",
    logo3: "photoshop",
    logo4: "illustrator"
  },
  slideRenderEsp: {
    name: "Render Espacios",
    image: [
      'http://imagenes360.net/fotos/renders/esp/espacios_01.JPG',
      'http://imagenes360.net/fotos/renders/esp/espacios_02.jpg',
      'http://imagenes360.net/fotos/renders/esp/espacios_03.JPG',
      'http://imagenes360.net/fotos/renders/esp/espacios_04.JPG',
      'http://imagenes360.net/fotos/renders/esp/espacios_05.JPG',
      'http://imagenes360.net/fotos/renders/esp/espacios_06.JPG',
      'http://imagenes360.net/fotos/renders/esp/espacios_07.JPG',
      'http://imagenes360.net/fotos/renders/esp/espacios_08.JPG',
      'http://imagenes360.net/fotos/renders/esp/espacios_09.JPG',
      'http://imagenes360.net/fotos/renders/esp/espacios_10.JPG',
      'http://imagenes360.net/fotos/renders/esp/espacios_11.jpg',
      'http://imagenes360.net/fotos/renders/esp/espacios_12.jpg',
      'http://imagenes360.net/fotos/renders/esp/espacios_13.JPG',
      'http://imagenes360.net/fotos/renders/esp/espacios_14.JPG',
      'http://imagenes360.net/fotos/renders/esp/espacios_15.jpg',
      'http://imagenes360.net/fotos/renders/esp/espacios_16.jpg'
    ],
    commentsPerPic: [
      "Apartamento Las Vegas | Salón",
      "Apartamento Las Vegas | Comedor",
      "Apartamento Las Vegas | Vista Superior",
      "Casa Containers | Baño",
      "Casa Containers | Vista Superior",
      "Barco | Puente Cañonero",
      "Mariposario La Trinidad | Lago",
      "Mariposario La Trinidad | Deck",
      "Casa Rionegro | Salón",
      "Casa Rionegro | Cocina",
      "Bosques de Zuñiga | Vista Superior",
      "Bosques de Zuñiga | Vista Superior",
      "Apartamento San Juan de la Vega | Oficina",
      "Apartamento San Juan de la Vega | Cuarto",
      "Cocina | Diseño Puerta",
      "Academia Brazada | Vista General"
    ],
    description: "Los renders de espacios son imágenes ideales para visualizar un ambiente que aún no existe o para diseñar reformas y decoración.\nEstas gráficas son realizadas mediante técnicas de fotorealismo utlizando diferentes softwares de modelación 3D, renderizado y post producción.",
    logo1: "tridimax",
    logo2: "vray",
    logo3: "photoshop",
    logo4: "illustrator"
  },
}
